#!/usr/bin/env ruby

require 'trollop'

conf = Trollop::options do
  banner "avg < <one number per line>"
  opt :round, "Number of digits after decimal point.", :type => :int, :default => -1
end

sum = 0.0
i = 0
while line = STDIN.gets
  sum += line.to_f
  i +=1
end

avg = sum/i.to_f

if conf[:round] >= 0
  puts avg.round conf[:round]
else
  puts avg
end

