#!/usr/bin/env zsh

SHUF=$(which shuf)
if [[ $? -ne 0 ]]; then
  SHUF=$(which gshuf)
  if [[ $? -ne 0 ]]; then
    echo "no `shuf` found, exiting"
    exit
  fi
fi


get_random() { seed="$1"; openssl enc -aes-256-ctr -pass pass:"$seed" -nosalt < /dev/zero 2>/dev/null; }

echo "shuffling ..."
$SHUF --random-source=<(get_random 42) $1 > $1.shuf
$SHUF --random-source=<(get_random 42) $2 > $2.shuf

