#!/bin/sh


egrep -v "^[[:space:]]*(<\?xml.*\?>|</?(mteval|doc|srcset|refset)[^>]*>)[[:space:]]*$" \
  | egrep -v "^[[:space:]]*<(url|description|keywords|talkid|title)>.*</(url|description|keywords|talkid|title)>[[:space:]]*$" \
  | sed "s|<seg[^>]*>\s*||" | sed "s|\s*</seg>$||"

