#!/usr/bin/env ruby

require 'zipf'
require 'trollop'

def main
  conf = Trollop::options do
    opt :input, "input", :type => :string, :default => '-'
    opt :references, "references", :type => :string, :required => true
    opt :len_hack, "hack of Nakov et al", :type => :int, :default => 0
    opt :n, "N", :default => 4
  end

  refs = ReadFile.readlines_strip conf[:references]
  i = -1
  input = ReadFile.new conf[:input]
  while line = input.gets
    i += 1
    if line.strip == ''
      puts 0.0
      next
    end
    puts BLEU::per_sentence_bleu line.strip, refs[i], conf[:n], conf[:len_hack]
  end
  input.close
end

main

