#!/usr/bin/env ruby

require 'trollop'


opts = Trollop::options do
  banner "sample --size <n> --population <n>"
  opt :size, "Sample size (percentage).", :type => :int
  opt :population, "'Population' (number \in N)", :type => :int
end

prng = Random.new(Random.new_seed)
1.upto(opts[:population]) { |i|
  puts i if prng.rand(1..opts[:size])==0
}

