#!/usr/bin/env ruby

require 'zipf'

def write_kbest l, fn
  f = WriteFile.new fn
  f.write l.join("")
  f.close
end

dir = ARGV[0]
i = 0
l = []
while line = STDIN.gets
  j = line.split.first.to_i
  if j == 0 && l.size > 0
    write_kbest l, "#{dir}/#{i}.gz"
    l = []
    i += 1
  end
  l << line
end
write_kbest l, "#{dir}/#{i}.gz" # last one

